logging:
  config: classpath:logback.xml
application:
  alertmanager:
    targetKey: team:{{ .commonLabels.team }}
    title: ''
    message: ''
  phone:
    use: true
    url: http://localhost:9000/send?phoneNum={{ .phone }}&msg={{ .message }}&callbackNum=01050078766
    method: GET
    body: ''
    format: delimiter
  email:
    use: true
    host: smtp.gmail.com
    port: 587
    auth: true
    username: abcd@gmail.com
    password: zgtgfteyivkzrsdf
  slack:
    use: true
  msteams:
    use: true
  webhook:
  proxy:
    use: false
    url: http://172.22.134.22

---
spring:
  profiles: container
my:
  servers:
    - aaa-default.bar.com
    - bbb-default.bar.com
