server:
  port: 8080
logging:
  config: classpath:logback.xml
application:
  alertmanager:
    targetId: team:{{ .commonLabels.team }}
  email:
    host: smtp.gmail.com
    port: 587
    auth: true
    username: abcd@gmail.com
    password: zgtgfteyivkzrsdf
  slack:
    url: https://hooks.slack.com/services/
  webhook:
  proxy:
    use: false
    url: http://172.22.134.22
